### ISSUE TITLE
[Bug]: 版本更新1.3.9后，eslint 从9.14.0升级到9.15.0，出现Cannot read properties of undefined (reading 'allowShortCircuit')

### ISSUE THREAD

**Issue by today5040** [soybeanjs/soybean-admin#674]
### 软件版本

1.3.9

### 运行环境

Windows (64)

### 运行架构

x86

### 重现步骤

更新完执行pnpm lint报错：
`> eslint . --fix

Oops! Something went wrong! :(

ESLint: 9.15.0

TypeError: Error while loading rule '@typescript-eslint/no-unused-expressions': Cannot read properties of undefined (reading 'allowShortCircuit')
Occurred while linting D:\dev\projects\netcore\osharp\Presentation\ui\osharp-vue-ts\build\config\index.ts
    at Object.create (D:\dev\projects\netcore\osharp\Presentation\ui\osharp-vue-ts\node_modules\.pnpm\eslint@9.15.0_jiti@2.4.0\node_modules\eslint\lib\rules\no-unused-expressions.js:75:13)
    at create (D:\dev\projects\netcore\osharp\Presentation\ui\osharp-vue-ts\node_modules\.pnpm\@typescript-eslint+eslint-plugin@8.11.0_@typescript-eslint+parser@8.11.0_eslint@9.15.0_jiti@2_xk4a4ejmtdd4zdg4x74r6vho2u\node_modules\@typescript-eslint\eslint-plugin\dist\rules\no-unused-expressions.js:28:32)
    at Object.create (D:\dev\projects\netcore\osharp\Presentation\ui\osharp-vue-ts\node_modules\.pnpm\@typescript-eslint+utils@8.11.0_eslint@9.15.0_jiti@2.4.0__typescript@5.6.3\node_modules\@typescript-eslint\utils\dist\eslint-utils\RuleCreator.js:31:20)
    at createRuleListeners (D:\dev\projects\netcore\osharp\Presentation\ui\osharp-vue-ts\node_modules\.pnpm\eslint@9.15.0_jiti@2.4.0\node_modules\eslint\lib\linter\linter.js:944:21)
    at D:\dev\projects\netcore\osharp\Presentation\ui\osharp-vue-ts\node_modules\.pnpm\eslint@9.15.0_jiti@2.4.0\node_modules\eslint\lib\linter\linter.js:1082:84
    at Array.forEach (<anonymous>)
    at runRules (D:\dev\projects\netcore\osharp\Presentation\ui\osharp-vue-ts\node_modules\.pnpm\eslint@9.15.0_jiti@2.4.0\node_modules\eslint\lib\linter\linter.js:1013:34)
    at #flatVerifyWithoutProcessors (D:\dev\projects\netcore\osharp\Presentation\ui\osharp-vue-ts\node_modules\.pnpm\eslint@9.15.0_jiti@2.4.0\node_modules\eslint\lib\linter\linter.js:1911:31)
    at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (D:\dev\projects\netcore\osharp\Presentation\ui\osharp-vue-ts\node_modules\.pnpm\eslint@9.15.0_jiti@2.4.0\node_modules\eslint\lib\linter\linter.js:1993:49)
    at Linter._verifyWithFlatConfigArray (D:\dev\projects\netcore\osharp\Presentation\ui\osharp-vue-ts\node_modules\.pnpm\eslint@9.15.0_jiti@2.4.0\node_modules\eslint\lib\linter\linter.js:2082:21)
    at #processPending (D:\dev\projects\netcore\osharp\Presentation\ui\osharp-vue-ts\node_modules\.pnpm\@humanwhocodes+retry@0.4.1\node_modules\@humanwhocodes\retry\dist\retrier.cjs:399:19)
    at D:\dev\projects\netcore\osharp\Presentation\ui\osharp-vue-ts\node_modules\.pnpm\@humanwhocodes+retry@0.4.1\node_modules\@humanwhocodes\retry\dist\retrier.cjs:313:33
    at <anonymous>

Oops! Something went wrong! :(

ESLint: 9.15.0

AbortError: The operation was aborted
    at checkAborted (node:internal/fs/promises:472:11)
    at readFileHandle (node:internal/fs/promises:515:3)
    at Object.readFile (node:internal/fs/promises:1243:24)
 ELIFECYCLE  Command failed with exit code 2.`

### 期望的结果是什么？

是和这个问题一样吗？
https://github.com/typescript-eslint/typescript-eslint/issues/10353
https://github.com/typescript-eslint/typescript-eslint/issues/10342

### 实际的结果是什么？

我暂时把eslint版本降到9.14.0,运行正常。

**Comment by honghuangdc** [comment]
04f334a
